---
grails:
    profile: web
    codegen:
        defaultPackage: persona
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''
environments:
  development:
    dataSource:
      dbCreate: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 4321
      url: jdbc:postgresql://localhost/persona
  test:
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  production:
    dataSource:
      dbCreate: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 1234
      url: jdbc:postgresql://localhost/persona
      properties:
        maxActive: 50
        maxIdle: 25
        minIdle: 5
        initialSize: 5
        minEvictableIdleTimeMillis: 1800000
        timeBetweenEvictionRunsMillis: 1800000
        maxWait: 10000
        ValidationQuery: "select 1"
        validationQueryTimeout: 3
        validationInterval: 15000
server:
  port: 8080  # Cambia el puerto a 9090
  servlet:
    context-path: /persona  # Cambia el contexto a /miapp
